
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Puneet
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    Connection connection;
    Statement statement;
    
    public Register() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendancemanager", "root", "puneet");
            statement = connection.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        fNameTextBox = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        uNameTextBox = new javax.swing.JTextField();
        passwdTextBox = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Register");

        fullname.setText("Full Name");
        fullname.setMaximumSize(new java.awt.Dimension(65, 15));
        fullname.setMinimumSize(new java.awt.Dimension(65, 15));
        fullname.setPreferredSize(new java.awt.Dimension(65, 15));

        username.setText("Username");
        username.setMaximumSize(new java.awt.Dimension(65, 15));
        username.setMinimumSize(new java.awt.Dimension(65, 15));
        username.setPreferredSize(new java.awt.Dimension(65, 15));

        password.setText("Password");
        password.setMaximumSize(new java.awt.Dimension(65, 15));
        password.setMinimumSize(new java.awt.Dimension(65, 15));
        password.setPreferredSize(new java.awt.Dimension(65, 15));

        fNameTextBox.setMaximumSize(new java.awt.Dimension(190, 20));
        fNameTextBox.setMinimumSize(new java.awt.Dimension(190, 20));
        fNameTextBox.setPreferredSize(new java.awt.Dimension(190, 20));

        register.setText("Register");
        register.setMaximumSize(new java.awt.Dimension(80, 21));
        register.setMinimumSize(new java.awt.Dimension(80, 21));
        register.setPreferredSize(new java.awt.Dimension(80, 21));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.setMaximumSize(new java.awt.Dimension(80, 21));
        exit.setMinimumSize(new java.awt.Dimension(80, 21));
        exit.setPreferredSize(new java.awt.Dimension(80, 21));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        uNameTextBox.setMaximumSize(new java.awt.Dimension(190, 20));
        uNameTextBox.setMinimumSize(new java.awt.Dimension(190, 20));
        uNameTextBox.setPreferredSize(new java.awt.Dimension(190, 20));

        passwdTextBox.setMaximumSize(new java.awt.Dimension(190, 20));
        passwdTextBox.setMinimumSize(new java.awt.Dimension(190, 20));
        passwdTextBox.setPreferredSize(new java.awt.Dimension(190, 20));
        passwdTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwdTextBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Click here to Log in");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(uNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        try{
            connection.close();
            System.exit(0);
        }catch(Exception e){
            System.out.println("Unknown Error");
        }        
    }//GEN-LAST:event_exitActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        if (fNameTextBox.getText().isEmpty() || uNameTextBox.getText().isEmpty() || passwdTextBox.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter credentials before continuing");
        }
        else{
            String fname,username;
            fname=fNameTextBox.getText();
            username=uNameTextBox.getText();
            char[] pwd=passwdTextBox.getPassword();
            String passString = new String(pwd);
            String insert="insert into registered_users values('"+(fname)+"','"+(username)+"','"+(passString)+"')";
            String insert1="insert into attendancegoal values('"+(username)+"',85)";
            try{
                statement.executeUpdate(insert);
                statement.executeUpdate(insert1);
                JOptionPane.showMessageDialog(this, "Registration Successful");
                connection.close();
                this.dispose();
                new Login().setVisible(true);
            }
            catch(java.sql.SQLIntegrityConstraintViolationException e){
                //JOptionPane.showMessageDialog(this, "Username alredy exists!");
                JOptionPane.showMessageDialog(this, "Username alredy exists!", "Registration Failed", JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(this, "Unknown Error", "Error", JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setText("<HTML><U>Click here to Log in</U></HTML>");
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setText("Click here to Log in");
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        try{
            connection.close();
            this.dispose();
            new Login().setVisible(true);
        }catch(Exception e){
            System.out.println("Unknown Error");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void passwdTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdTextBoxActionPerformed
        // TODO add your handling code here:
        //System.out.println("HELLO");        
        registerActionPerformed(evt);
    }//GEN-LAST:event_passwdTextBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JTextField fNameTextBox;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwdTextBox;
    private javax.swing.JLabel password;
    private javax.swing.JButton register;
    private javax.swing.JTextField uNameTextBox;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
